[package]
name = "zloopctl"
version = "0.1.0"
edition = "2024"
license-file = "COPYING.GPL"
license = "GPL-2.0"

[dependencies]
clap = "4.5.49"

[dependencies.rustix]
version = "1.1.2"
features = ["fs"]
